HID Mouse with absolute positioning
hathach/tinyusb pull request #1363
Opened 2022-03-02 14:04 UTC by tobozo

The current mouse support is limited to relative positioning.

This PR adds absolute mouse descriptor template and descriptors.

2022-03-02 15:12 UTC, me-no-dev commented on src/class/hid/hid.h
> +} abs_mouse_report_t;
to follow the naming of the rest of the structs, this should be renamed to `hid_abs_mouse_report_t`

2022-04-24 22:31 UTC, FallingSnow commented
@tobozo Please fix test errors.

2022-04-24 23:49 UTC, tobozo commented
@FallingSnow fetching upstream fixed it on my fork

https://github.com/tobozo/tinyusb/runs/6149927028?check_suite_focus=true

2022-11-16 21:23 UTC, tao-j approved these changes
LGTM

2023-03-30 19:18 UTC, earlephilhower requested changes
@tobozo this is great, but if `abs_mouse` is to be a first-class citizen in TinyUSB, shouldn't we add a couple helper functions to hid_device.h to match the base mouse?

Like:
````
bool tud_hid_n_abs_mouse_report(uint8_t instance, uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal);`

static inline bool tud_hid_abs_mouse_report(uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal)
{
  return tud_hid_n_abs_mouse_report(0, report_id, buttons, x, y, vertical, horizontal);
}
````

2023-03-30 19:50 UTC, tobozo commented
@earlephilhower thanks for the suggestion :+1:  should I also add the C function in hid_device.c ?

```C
bool tud_hid_n_abs_mouse_report(uint8_t instance, uint8_t report_id, uint8_t buttons, int16_t x, int16_t y, int8_t vertical, int8_t horizontal)
{
  hid_abs_mouse_report_t report =
  {
    .buttons = buttons,
    .x       = x,
    .y       = y,
    .wheel   = vertical,
    .pan     = horizontal
  };
  return tud_hid_n_report(instance, report_id, &report, sizeof(report));
}
```

2023-03-30 19:54 UTC, earlephilhower commented
Yes, that would be needed since we only have the prototype otherwise which will make the linker unhappy. :)

2023-03-30 21:29 UTC, tobozo commented
ideally the touch zone should have a shape proportional to the target screen so it's not exactly as intuitive as using the relative mouse, especially when the desktop has multiple screens :sweat:  

there are a lot of use cases anyway, I remember exploring those with an ESP32-S2:

- physical mouse
- physical touchpad (e.g. using a XPT2046)
- mouse server (e.g. forwards mouse reports from a http client to the host)
- scripted mouse (e.g. [drawing hand in an image editor](https://www.youtube.com/watch?v=Nsf1brl3z0w))

2023-07-13 10:35 UTC, doge-gif commented
@earlephilhower May I know what's blocking this merge?

2023-07-13 17:49 UTC, earlephilhower commented
@doge-gif this isn't my repo or PR, so you'll need to ask @hathach . 😄    I've implemented it in the [arduino-pico](https://github.com/earlephilhower/arduino-pico) core already and will undo my private hacks once this PR merges and the Raspberry Pi team updates their SDK to include it.

2023-10-05 08:27 UTC, tobozo commented
@me-no-dev does this need further review? Looks like it's missing your approval

poke @hathach 

![image](https://github.com/hathach/tinyusb/assets/1893754/19b7772b-391d-4e36-b4f5-00ef7623bfd3)

2023-10-05 08:56 UTC, me-no-dev approved these changes

2023-10-05 08:58 UTC, me-no-dev commented
Sorry @tobozo ! Done.

2023-10-26 10:39 UTC, ithinkido commented
Please can this get merged

2023-12-29 02:25 UTC, thewh1teagle commented
What's the status of this PR? is it going to be merged?

2023-12-29 03:24 UTC, hathach commented
Unfortunately, I still havent got time to look at this. Will do whenever possible

2023-12-29 11:12 UTC, thewh1teagle commented
It's nearly 50 lines and a year ago :)
Hope you get time to check it out.
By the way, can we use the same device for absolute and relative in the same descriptor or it has to be 2 different devices?

2024-04-08 11:33 UTC, hathach approved these changes
thank you very much for the PR and sorry for late response. I kind of forgot about these in my pile of email.

2024-04-08 11:33 UTC, merged