Add support for MJPG on UVC
hathach/tinyusb pull request #1668
Opened 2022-10-09 12:08 UTC by kkitayam

**Describe the PR**
Add support for MJPG on UVC.

It is tested with `video_capture` example on `frdm_kl25z` and `raspberry pi pico`

**Additional context**
`video_capture` uses MJPG video instead of uncompressed video when it builds with `CFG_EXAMPLE_VIDEO_READONLY` defined.

If a MCU has not enough SRAM for frame buffers, `CFG_EXAMPLE_VIDEO_READONLY` is already defined in `board.mk` at `hw/bsp/<board>`. For example, `frdm_kl25z` and so on.  Any other MUC which has enough SRAM for frame buffers use uncompressed video in default. To force the use of MJPG video, add the `FORCE_READONLY` argument to make or cmake.
For example:
```console
make FORCE_READONLY=1 BOARD=frdm_kl25z
cmake -B build_rp2040 -G Ninja -DFAMILY=rp2040 -DPICO_SDK_PATH=c:\pico_sdk -DFORCE_READONLY=1
```

2022-10-09 12:24 UTC, kkitayam commented
@me-no-dev 

Would you see if this PR is useful or not for your application which indicated https://github.com/hathach/tinyusb/pull/1118#issuecomment-939278418 ?

2022-10-11 15:18 UTC, tswan-quasi requested changes
I only checked the descriptors and class files as that is what I used in my setup. Some type consistency changes that also affect the functionality. Regardless, it runs fine on my setup, tested on LPC55S69.

2022-10-11 15:18 UTC, tswan-quasi commented on src/class/video/video_device.c
> +  };
could expand packed struct to also include bmCapabilities, wWidth, wHeight, dwMinBitRate, and dwMaxBitRate. They are common between the 3 types

2022-10-11 15:18 UTC, tswan-quasi commented on src/class/video/video_device.c
>      tusb_desc_cs_video_frm_uncompressed_t const *frm = _find_desc_frame(tu_desc_next(fmt), end, frmnum);
line 470, 485, 494, 495 should all have the pointer type changed for consistency as well as functionality (in some cases)

`tusb_desc_cs_video_frm_uncompressed_t` --> `tusb_desc_cs_video_frm_t`

`tusb_desc_cs_video_fmt_uncompressed_t` --> `tusb_desc_cs_video_fmt_t`

2022-10-12 10:49 UTC, kkitayam commented on examples/device/video_capture/src/usb_descriptors.h
> +#define TUD_VIDEO_CAPTURE_DESC_MJPG_LEN (\
That's good!

2022-10-12 12:05 UTC, kkitayam commented
@tswan-quasi 
Thank you for your helpful comments. I feel that your comments helped improve this PR.

2022-10-19 16:10 UTC, merged