Log outbound xfer bytes while in debug
hathach/tinyusb pull request #2421
Opened 2024-01-22 22:24 UTC by antoniovazquezblanco

**Describe the PR**
This simple PR logs outbound xfer bytes when log level is set to debug. It is useful to be able to dissect the full conversation and not only incoming packets.
While this may be too verbose, it is quite useful when things go south.

**Additional context**
This is really nice in combination with a simple USB dissector. I am currently using scapy to parse the logs. I may create a PR to scapy with the relevant USB layers and may post an example on how to use them in a future PR.

2024-01-23 06:15 UTC, hathach commented
It is helpful but too verbose, it could introduce other timing issues. Especially with bulk transfer like msc class. We should increase the log level to at least 3 for this info.

2024-01-23 08:59 UTC, antoniovazquezblanco commented
Done! :D

2024-02-06 09:39 UTC, hathach requested changes
checkout review for request changes

2024-02-06 09:39 UTC, hathach commented on src/device/usbd.c
> +  TU_LOG3_BUF(buffer, total_bytes);
must check if this is an IN transfer, otherwise, data contents is meaningless. It must be wrapped in `#if CFG_TUD_LOG_LEVEL >= 3`

2024-02-07 12:08 UTC, antoniovazquezblanco commented
Made the requested changes. Also improved a bit on the previous solution.

Thank you for being so patient with this minuscule PR. it is helping me learn more about the project!

2024-04-04 10:16 UTC, hathach approved these changes
look good, thank you. I update it a bit to use dir variable, will merge when ci passed

2024-04-04 11:34 UTC, merged