[add]Add rtthread script support.
hathach/tinyusb pull request #2599
Opened 2024-04-16 05:24 UTC by Rbb666

…ojects.

**Describe the PR**
Add rtthread script support to better integrate into rtthread projects.
Tinyusb will be added to the rtthread project in the form of a software package.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

2024-04-16 14:02 UTC, hathach requested changes
`src/` is for tinyusb stack code, lots of pr's files are framework glue codes and does not belong to src/ folder. If rtthread needs these glue code to run, you can put it into `lib/` instead.

2024-04-17 01:44 UTC, Rbb666 commented
> 感谢您的 PR，但它更像是一个示例配置，应该添加到 rt-thread 而不是 tinyusb。
> 
> 使用您的宏只会使事情变得更加复杂，需要检查更多条件并且仅支持 CDC+MSC，如果有人只是想要 2*CDC 怎么办？ 应专门编写申请。`tusb_descriptor.c/.h`

Hello, by doing this you can add the tinyusb repo as the rtthread package to the project. This form is similar to the LVGL project: https://github.com/lvgl/lvgl/tree/master/env_support/rt-thread

2024-04-17 01:44 UTC, Rbb666 commented
> `src/` is for tinyusb stack code, lots of pr's files are framework glue codes and does not belong to src/ folder. If rtthread needs these glue code to run, you can put it into instead.`lib/`

OK,I'll modify it.

2024-04-17 07:57 UTC, HiFiPhile commented
> Hello, by doing this you can add the tinyusb repo as the rtthread package to the project. This form is similar to the LVGL project: https://github.com/lvgl/lvgl/tree/master/env_support/rt-thread

Tinyusb has much more configurations than LVGL, it's impossible to cover every use case in a single `tusb_config.h` and `tusb_descriptor.c/.h`. That's why every example has its own configurations.

For example if you compare `tusb_descriptor.c` from `video_capture` and `usb_msc` examples there is nearly nothing in common.

These file should be removed.

2024-04-17 09:01 UTC, Rbb666 commented
> > 您好，通过这样做，您可以将 tinyusb 存储库作为 rtthread 包添加到项目中。此表单类似于 LVGL 项目：https://github.com/lvgl/lvgl/tree/master/env_support/rt-thread
> 
> Tinyusb 的配置比 LVGL 多得多，不可能在单个 和 中涵盖所有用例。这就是为什么每个示例都有自己的配置。`tusb_config.h``tusb_descriptor.c/.h`
> 
> 例如，如果比较 from 和 example，则几乎没有任何共同点。`tusb_descriptor.c``video_capture``usb_msc`
> 
> 应删除这些文件。

OK.

2024-04-18 01:53 UTC, Rbb666 commented
> > Hello, by doing this you can add the tinyusb repo as the rtthread package to the project. This form is similar to the LVGL project: https://github.com/lvgl/lvgl/tree/master/env_support/rt-thread
> 
> Tinyusb has much more configurations than LVGL, it's impossible to cover every use case in a single `tusb_config.h` and `tusb_descriptor.c/.h`. That's why every example has its own configurations.
> 
> For example if you compare `tusb_descriptor.c` from `video_capture` and `usb_msc` examples there is nearly nothing in common.
> 
> These files should be removed.

It has been modified, please take a look again.

2024-04-25 04:48 UTC, hathach approved these changes
I pushed a fix for pre-commmit. Look good, note that since I don't ( know how to) use rtthread yet, I won't be able to maintain the code, please submit PR to help keep it up to date.

2024-04-25 04:48 UTC, merged

2024-04-25 09:13 UTC, Rbb666 commented
> 我推送了 pre-commit 的修复程序。看起来不错，请注意，由于我还不知道如何使用 rtthread，我将无法维护代码，请提交 PR 以帮助使其保持最新状态。

No problem, I am an official member of rtthread and can help you maintain it.