add basic support for rt-thread
hathach/tinyusb pull request #637
Opened 2021-02-07 14:53 UTC by tfx2001

**Describe the PR**
Add a basic support for RT-Thread RTOS. More about the [RT-Thread](https://www.rt-thread.io/).

**Additional context**
None.

2021-02-07 14:55 UTC, TAGORE-git commented
unsubscribe

On Sun, 7 Feb, 2021, 8:23 pm tfx2001, <notifications@github.com> wrote:

> *Describe the PR*
> Add a basic support for RT-Thread RTOS. More about the RT-Thread
> <https://www.rt-thread.io/>.
>
> *Additional context*
> None.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/hathach/tinyusb/pull/637
> Commit Summary
>
>    - add basic support for rt-thread
>
> File Changes
>
>    - *M* src/osal/osal.h
>    <https://github.com/hathach/tinyusb/pull/637/files#diff-cd2fc0ca5d617486fbfcfe29fecce1f00a3acfc4bdc18c450be62736d3a4df3a>
>    (2)
>    - *A* src/osal/osal_rtthread.h
>    <https://github.com/hathach/tinyusb/pull/637/files#diff-6d1f70e0bde0360c78db00dfb3d47d827de47a2fd12bd65c2a6398a97f828ee5>
>    (129)
>
> Patch Links:
>
>    - https://github.com/hathach/tinyusb/pull/637.patch
>    - https://github.com/hathach/tinyusb/pull/637.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/hathach/tinyusb/pull/637>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASSN2B5ERPMM5GTZ4HONSZLS52SQDANCNFSM4XHQYJOA>
> .
>

2021-02-08 08:47 UTC, hathach requested changes
PR lack define value for `OPT_OS_RTTHREAD`. Is it easy enough to add `cdc_msc_rtthread` example so that we could avoid building issue like this for future changes.

2021-02-08 10:50 UTC, tfx2001 commented
It is my mistake.  

I'm a student developer in university, and I am still studying embedded development. Maybe add `cdc_msc_rtthread` example is a little hard for me. I'm concerned about overlooking support for other MCUs.

In fact, the RT-Thread team already provides a USB Device stack in RT-Thread, but not in RT-Thread Nano (the RTOS kernel of RT-Thread). I hope to provide more options for Chinese developers.

Thank you for your review.

2021-02-08 11:05 UTC, hathach commented
no problem at all if you think adding the example is not trivial, though have you been able to run rt-thread with tinyusb successfully on their studio IDE ?

2021-02-08 12:25 UTC, tfx2001 commented
Yes. I have tested it in RT-Thread Studio, I've also tested it in my own CMake project with RT-Thread Nano. They all work fine.

2021-02-08 12:33 UTC, hathach reviewed
Thanks for the PR, It looks good. There is only a request to suppress unused warning and a bit of code style. Afterwards this should be good for the merge

2021-02-08 12:33 UTC, hathach commented on src/osal/osal_rtthread.h
> +    return rt_sem_release(sem_hdl) == RT_EOK;
please add the cast to prevent compiler to throw unused warning 

```
(void) in_isr;
```

2021-02-08 12:33 UTC, hathach commented on src/osal/osal_rtthread.h
> +    return rt_mq_send(qhdl, (void *)data, qhdl->msg_size) == RT_EOK;
same as above to avoid unused warning.

2021-02-08 12:33 UTC, hathach commented on src/osal/osal_rtthread.h
> +        .depth = _depth, .item_sz = sizeof(_type), .buf = _name##_##buf};
please merge this 2 line together, also needs a space between `##buf `and closing `}`

2021-02-08 12:33 UTC, hathach commented
> Yes. I have tested it in RT-Thread Studio, I've also tested it in my own CMake project with RT-Thread Nano. They all work fine.

That is good enough for this PR

2021-02-08 12:49 UTC, hathach approved these changes
look good, thanks for the PR. Will merge when ci complete

2021-02-08 13:10 UTC, merged