Add alternate bitfield padding option
hathach/tinyusb pull request #654
Opened 2021-02-16 15:47 UTC by xmos-jmccarthy

Adds configuration option CFG_TUSB_ALT_BIT_PACKING_ALIGNMENT, which substitutes bitfield variable " : 0" padding syntax with an unused variable of size equal to the remaining number of bits.

This change is intended to resolve aligned access issues for some platforms.

The default behaviour is original if the option is not explicitly enabled.  Consequently, this change should not affect existing applications.

2021-02-16 19:15 UTC, niepiekm approved these changes

2021-02-17 07:11 UTC, hathach commented
thank you for your PR, would you mind telling me what is your platform you are working. unnamed zero size is pretty much std padding in C language.

2021-02-17 15:10 UTC, xmos-jmccarthy commented
I am working on the XCore platform.

Unnamed zero size is indeed standard; However, I found that the compiler for XCore currently will cause a hardware exception when trying to access a bitfield under certain alignment conditions.

2021-02-18 05:44 UTC, hathach requested changes
Thanks for the PR, actually, the `bitfield size = 0` is due to my laziness. Since you already counted the unused size, there is no need to introduce the new macro `CFG_TUSB_ALT_BIT_PACKING_ALIGNMENT`, we should just always use it which is more explicit (therefore more portable). Would you mind updating the PR accordingly.

PS: also it is better to use the  `TU_RESERVED` instead of `unused`, it expands to unique token name. But it is optional.

2021-02-19 04:03 UTC, hathach approved these changes
look great, thank you for your PR.

2021-02-19 04:03 UTC, merged