Add MM32 SDK and USB driver
hathach/tinyusb pull request #869
Opened 2021-06-02 01:49 UTC by zhangslice

Signed-off-by: zhangslice <1304224508@qq.com>

**Describe the PR**
A clear and concise description of what this PR solve.

**Additional context**
If applicable, add any other context about the PR and/or screenshots here.

2021-06-02 04:25 UTC, hathach reviewed
the hw/mcu should be added as submodule, do mindmotion has github repo for mm322 sdk. else I will help and make one and push update to this PR for you guys.

2021-06-02 05:16 UTC, zhangslice commented
The following repository can be used, and the SDK will be updated if there are any updates or additions
https://github.com/zhangslice/mm32sdk


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hathach/tinyusb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 中午12:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hathach/tinyusb] Add MM32 SDK and USB driver (#869)





 
@hathach commented on this pull request.
 
the hw/mcu should be added as submodule, do mindmotion has github repo for mm322 sdk. else I will help and make one and push update to this PR for you guys.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-02 06:14 UTC, hathach commented
> The following repository can be used, and the SDK will be updated if there are any updates or additions https://github.com/zhangslice/mm32sdk

thanks that repo would be useful, I notice that both Keil_core and IAR_Core within the cmsis is the same, without any file differences. you should just have it as `CSMSIS/Core` https://github.com/zhangslice/mm32sdk/tree/main/mm32f327x/CMSIS

do you want to merge them together ? I am fine If you still want to keep it that way though.

2021-06-02 06:24 UTC, hathach commented
Ok thanks for letting me, in general you should not modify those file since they are from ARM which already taken care of the keil/gcc/iar. But that is up to you.

2021-06-02 06:30 UTC, zhangslice commented
Well, thank you, that's a good suggestion




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hathach/tinyusb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月2日(星期三) 下午2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hathach/tinyusb] Add MM32 SDK and USB driver (#869)





 
Ok thanks for letting me, in general you should not modify those file since they are from ARM which already taken care of the keil/gcc/iar. But that is up to you.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2021-06-02 06:38 UTC, hathach requested changes
I pushed the update to your master branch on your fork, please pull before making any other commit and update. There are 2 requests for change as follows:
- MIT license is required for `dcd_mm32f327x_otg.c`
- `tinyusb_keil.zip` must be removed

2021-06-02 06:38 UTC, hathach commented on src/portable/mm32/dcd_mm32f327x_otg.c
> +/// <H2><CENTER>&COPY; COPYRIGHT MINDMOTION </CENTER></H2>
copyright for the drivers file that is within `/src` must be MIT license to be compatible with the rest of the project. Please consult your company and put the MIT license here if you are willing to move forward with the PR.

2021-06-02 18:25 UTC, hathach commented on src/portable/mm32/dcd_mm32f327x_otg.c
> +/// <H2><CENTER>&COPY; COPYRIGHT MINDMOTION </CENTER></H2>
Note: only this file need to be MIT license. Other driver in your sdk does not need to change at all

2021-06-07 10:21 UTC, hathach approved these changes
The port still need bsp to verify that mcu work with existing project on mm32. However, it is good as intial PR.

Note: I have removed the keil project .zip, such as binary file is not allowed in this repo. You could probably provide it as additional, add-on to your sdk.

2021-06-07 10:32 UTC, merged